"""Các trục phong cách Jev dùng để phân loại tác phẩm (câu hỏi Choice). 'unclear' cho phép Jev không bị ép chọn."""

AXES = {
    "medium": {
        "q": "Which medium or production method does this artwork appear to use?",
        "labels": {
            "watercolor": "Transparent water-based paint, washes, blooms",
            "oil_acrylic": "Opaque traditional paint with visible brush texture",
            "ink_pen": "Ink, pen, brush-pen or marker linework on paper",
            "pencil_charcoal": "Graphite, charcoal, pastel or other dry drawing media",
            "digital_painting": "Digitally painted raster artwork with brush strokes",
            "vector_flat": "Clean vector or flat-color digital illustration",
            "pixel": "Pixel art with visible pixel grid",
            "render_3d": "3D modeled and rendered image",
            "photo_manip": "Photograph, photo manipulation or photo-based composite",
            "collage_mixed": "Collage, cut paper, or mixed media assemblage",
            "craft_physical": "Physical craft: textile, embroidery, clay, sculpture, glass, mosaic",
            "unclear": "The description does not reveal the medium",
        },
    },
    "technique": {
        "q": "Which rendering technique dominates the image?",
        "labels": {
            "painterly": "Loose, visible strokes and blended color",
            "linework": "Outlines and line hatching carry the image",
            "flat_shapes": "Flat color shapes with little shading",
            "realistic_detail": "High-detail, realistic lighting and texture",
            "geometric": "Geometric construction, low-poly, isometric or hard-edged forms",
            "print_texture": "Printmaking look: halftone, risograph, linocut, grain",
            "glitch_distort": "Glitch, distortion, datamosh or digital artifacts",
            "ornamental": "Ornament, pattern, filigree or decorative repetition",
            "unclear": "Not determinable from the description",
        },
    },
    "palette": {
        "q": "Which palette family best matches the artwork's colors?",
        "labels": {
            "monochrome": "One hue or black-and-white/greyscale",
            "pastel": "Soft, light, desaturated colors",
            "earthy_muted": "Browns, ochres, olives, muted naturals",
            "neon_saturated": "Very saturated, neon or electric colors",
            "warm_dominant": "Reds, oranges and yellows dominate",
            "cool_dominant": "Blues, teals and purples dominate",
            "high_contrast": "Strong dark/light contrast with few mid-tones",
            "unclear": "Not determinable",
        },
    },
    "subject": {
        "q": "What is the main subject?",
        "labels": {
            "character_portrait": "A person or character, portrait or figure",
            "creature_fantasy": "Creature, monster, animal-like or fantasy being",
            "landscape_nature": "Landscape, plants, sky, natural scenery",
            "city_architecture": "Buildings, streets, interiors, cities",
            "object_still_life": "Objects, food, still life, items",
            "abstract_pattern": "No concrete subject; abstract forms or patterns",
            "scene_narrative": "A story moment with several elements interacting",
            "machine_vehicle": "Robots, mechs, vehicles, machinery",
            "unclear": "Not determinable",
        },
    },
    "mood": {
        "q": "What mood does the artwork convey?",
        "labels": {
            "serene": "Calm, peaceful, quiet",
            "melancholic": "Sad, nostalgic, lonely",
            "eerie_dark": "Dark, unsettling, horror-tinged",
            "playful": "Cute, whimsical, humorous, light-hearted",
            "dramatic_epic": "Grand, heroic, intense, cinematic",
            "energetic_chaotic": "Busy, loud, frantic, chaotic",
            "unclear": "Not determinable",
        },
    },
    "era": {
        "q": "Which historical movement or era does the style reference, if any?",
        "labels": {
            "none": "No clear historical or movement reference",
            "nouveau_deco": "Art Nouveau or Art Deco",
            "east_asian_trad": "Ukiyo-e, ink wash or other East Asian traditional art",
            "retro_80s_90s": "Retro 80s/90s, vaporwave, synthwave, early video games",
            "medieval_gothic": "Medieval, gothic, illuminated manuscript, stained glass",
            "scifi_futurist": "Sci-fi, cyberpunk, futurist",
            "folk_naive": "Folk art, naive art, tribal or craft traditions",
            "modernist_abstract": "Cubism, bauhaus, modernist abstraction",
            "impressionist": "Impressionism or post-impressionism",
            "unclear": "Not determinable",
        },
    },
}
